feat: add protected-route.ts and fix src/components/BookRating/index.tsx:123:51 - error TS2339: Property 'danger' does not exist on type - to Colors.error